spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.132.243.44:5432/tripin?useAffectedRows=true
    username: postgres
    password: tripin
    hikari:
      maxLifetime: 1765000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15   #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  http:
      encoding:
        charset: UTF-8
#        enable: true
        force: true

mybatis:
  ## Mybatis 配置
  # 配置为 com.pancm.bean 指向实体类包路径。
  type-aliases-package: com.tripin.application.entity
  # 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件
  mapper-locations: classpath:mapper/*.xml
